Repository OpenTree-Education/rhizone-lms, pull requests merged in 2022-11, with the labels that each got.

#417 #412 set up programs db infrastructure
  db/migration/V019__create_programs.sql
Labels: enhancement

#423 #422 Upgrade MUI icons-material package and its dependencies includin…
  webapp/yarn.lock
Labels: bug

#418 #414 Add calendar icon in the navbar which links to the calendar page
  webapp/src/components/App.tsx
  webapp/src/components/CalendarPage.tsx
  webapp/src/components/Navbar.tsx
Labels: enhancement

#421 #413 Insert default curriculum, including activities
  db/migration/V020__insert_default_activities.sql
Labels: enhancement

#420 #419 Add react-big-calendar
  webapp/package.json
  webapp/yarn.lock
Labels: enhancement

#426 #425 Add luxon and update other packages
  api/package.json
  api/yarn.lock
Labels: enhancement

#424 #416 Add home page link to the Rhizone logo in the Navbar
  webapp/src/components/Navbar.tsx
Labels: enhancement

#431 #430 Add Luxon as the localizer for react-big-calendar
  webapp/package.json
  webapp/yarn.lock
Labels: enhancement

#434 415 api route and service functions
  api/src/middleware/__tests__/programsRouter.ts
  api/src/middleware/programsRouter.ts
  api/src/models.d.ts
  api/src/server.ts
  api/src/services/__tests__/programsService.ts
  api/src/services/db.ts
  api/src/services/programsService.ts
  db/migration/V019__create_programs.sql
  db/migration/V020__insert_default_activities.sql
  webapp/src/types/api.d.ts
Labels: enhancement

#432 #427 Make a graphical representation of the programs and activities on the frontend side
  webapp/src/components/Activity.tsx
  webapp/src/components/CalendarPage.tsx
  webapp/src/components/Program.tsx
Labels: enhancement

#436 #429 Add new listProgramsWithActivities function and wrap up backend modifications
  api/src/middleware/__tests__/programsRouter.ts
  api/src/middleware/programsRouter.ts
  api/src/services/__tests__/programsService.ts
  api/src/services/programsService.ts
Labels: enhancement

#438 #437 Modifications to curriculum activities
  db/migration/V019__create_programs.sql
  db/migration/V020__insert_default_activities.sql
Labels: bug, enhancement

#435 #428 calendar view of activities
  webapp/src/components/Activity.tsx
  webapp/src/components/CalendarPage.tsx
  webapp/src/components/Program.tsx
Labels: enhancement

#439 #433: A React function-based approach
  webapp/src/components/App.tsx
  webapp/src/components/CalendarPage.tsx
  webapp/src/components/Program.tsx
  webapp/src/components/ProgramActivityDialog.tsx
  webapp/src/components/ProgramCalendar.tsx
  webapp/src/components/ProgramPicker.tsx
  webapp/src/components/ProgramsPage.tsx
Labels: enhancement

#441 #433 Import latest changes from Phoebe and the rest of the team
  webapp/src/components/ProgramActivityDialog.tsx
Labels: enhancement

#443 #433 Clickable Calendar Activities
  webapp/src/components/App.tsx
  webapp/src/components/CalendarPage.tsx
  webapp/src/components/Program.tsx
  webapp/src/components/ProgramActivityDialog.tsx
  webapp/src/components/ProgramCalendar.tsx
  webapp/src/components/ProgramPicker.tsx
  webapp/src/components/ProgramsPage.tsx
  webapp/src/types/api.d.ts
Labels: enhancement

#442 #440 Update packages to address security vulnerability
  api/package.json
  api/yarn.lock
  webapp/package.json
  webapp/yarn.lock
Labels: bug

#451 #445 Add popup in Calendar to enable the show more via popup feature in month view
  webapp/src/components/ProgramCalendar.tsx
Labels: enhancement
