Repository OpenTree-Education/rhizone-lms, pull requests merged in 2023-03, with the labels that each got.

#524 #523 Fix the reflections survey feature to use the renamed tables
  api/src/services/__tests__/questionnairesService.ts
  api/src/services/__tests__/reflectionsService.ts
  api/src/services/questionnairesService.ts
  api/src/services/reflectionsService.ts
Labels: bug, enhancement

#526 #525 Update Rhizone dependencies
  api/package.json
  api/src/server.ts
  api/yarn.lock
  docker-compose.yml
  webapp/package.json
  webapp/yarn.lock
Labels: enhancement

#528 #527 Increase MySQL healthcheck timeout from 2 to 10 minutes
  docker-compose.yml
Labels: bug

#530 #529 Address MySQL authentication deprecation by switching to mysql2 driver
  api/package.json
  api/src/services/db.ts
  api/yarn.lock
  docker-compose.yml
Labels: enhancement

#531 #517 Define routes for assessments feature
  api/src/models.d.ts
  webapp/src/types/api.d.ts
Labels: enhancement

#532 #516 helper service file and route
  api/src/middleware/__tests__/assessmentsDummyRouter.ts
  api/src/middleware/assessmentsDummyRouter.ts
  api/src/server.ts
  api/src/services/__tests__/assessmentsDummyService.ts
  api/src/services/assessmentsDummyService.ts
Labels: enhancement

#535 #534 Add assessment type to CurriculumAssessment
  api/src/models.d.ts
  webapp/src/types/api.d.ts
Labels: enhancement

#550 #549 Update Rhizone dependencies a second time
  api/.nvmrc
  api/Dockerfile
  api/package.json
  api/yarn.lock
  webapp/.nvmrc
  webapp/Dockerfile
  webapp/package.json
  webapp/src/helpers/__tests__/dateTime.ts
  webapp/yarn.lock
Labels: enhancement

#533 #514 Add a component for participants to view or take an assessment
  webapp/src/assets/data.ts
  webapp/src/components/App.tsx
  webapp/src/components/AssessmentDetailPage.tsx
  webapp/src/components/AssessmentDisplay.tsx
  webapp/src/components/AssessmentMetadataBar.tsx
  webapp/src/components/AssessmentQuestionCard.tsx
  webapp/src/components/AssessmentSubmitBar.tsx
  webapp/src/components/AssessmentsListPage.tsx
  webapp/src/types/api.d.ts
Labels: enhancement

#542 #538 Add test for assessment submission route
  api/src/middleware/__tests__/assessmentsRouter.ts
  api/src/models.d.ts
Labels: enhancement

#547 #536 Add tests for get assessments route
  api/src/middleware/__tests__/assessmentsRouter.ts
  api/src/middleware/assessmentsRouter.ts
Labels: enhancement

#554 #553 Update model files to reflect recent assessment features discussions
  api/package.json
  api/src/models.d.ts
  api/yarn.lock
  webapp/package.json
  webapp/src/assets/data.ts
  webapp/src/components/AssessmentDetailPage.tsx
  webapp/src/components/AssessmentDisplay.tsx
  webapp/src/components/AssessmentMetadataBar.tsx
  webapp/src/components/AssessmentQuestionCard.tsx
  webapp/src/components/AssessmentSubmitBar.tsx
  webapp/src/types/api.d.ts
  webapp/yarn.lock
Labels: enhancement

#556 #555 Update AssessmentResponse “response” to “response_text”
  api/src/models.d.ts
  api/src/services/__tests__/assessmentsDummyService.ts
  api/src/services/assessmentsDummyService.ts
  webapp/src/components/AssessmentDetailPage.tsx
  webapp/src/components/AssessmentQuestionCard.tsx
  webapp/src/components/AssessmentSubmitBar.tsx
  webapp/src/types/api.d.ts
Labels: enhancement

#559 #520 Reformat dummy data and components
  webapp/src/assets/data.ts
  webapp/src/components/AssessmentsListPage.tsx
  webapp/src/components/AssessmentsListTable.tsx
  webapp/src/components/AssessmentsListTabs.tsx
  webapp/src/components/Navbar.tsx
  webapp/src/types/api.d.ts
Labels: enhancement

#548 #543 Add frontend component for the page listing the submissions for a given assessment
  webapp/src/assets/data.ts
  webapp/src/components/App.tsx
  webapp/src/components/AssessmentSubmissionsListPage.tsx
  webapp/src/components/AssessmentsListTable.tsx
Labels: enhancement

#568 #563 Implement working functionality for the PUT /program/:programAssessmentId route
  api/src/assets/data.ts
  api/src/middleware/__tests__/assessmentsRouter.ts
  api/src/middleware/assessmentsRouter.ts
  api/src/services/__tests__/assessmentsService.ts
  api/src/services/assessmentsService.ts
Labels: enhancement

#569 #551 Implement working functionality for the GET / route
  api/src/assets/data.ts
  api/src/middleware/__tests__/assessmentsRouter.ts
  api/src/middleware/__tests__/assessmentsRouter.ts.515
  api/src/middleware/assessmentsRouter.ts
  api/src/middleware/assessmentsRouter.ts.515
  api/src/services/__tests__/assessmentsService.ts
  api/src/services/assessmentsService.ts
  api/src/services/assessmentsService.ts.515
Labels: enhancement

#566 #561 Implement working functionality for the GET /curriculum/:curriculumAssessmentId route
  api/src/assets/data.ts
  api/src/middleware/__tests__/assessmentsRouter.ts
  api/src/middleware/assessmentsRouter.ts
  api/src/services/__tests__/assessmentsService.ts
  api/src/services/assessmentsService.ts
Labels: enhancement

#573 #567 Implement working functionality for the GET /program/:programAssessmentId/submissions route
  api/src/assets/data.ts
  api/src/middleware/__tests__/assessmentsRouter.ts
  api/src/middleware/assessmentsRouter.ts
  api/src/services/__tests__/assessmentsService.ts
  api/src/services/assessmentsService.ts
Labels: enhancement

#574 #571 Implement functionality for the POST/assessments/program route
  api/src/assets/data.ts
  api/src/middleware/__tests__/assessmentsRouter.ts
  api/src/middleware/assessmentsRouter.ts
  api/src/services/__tests__/assessmentsService.ts
  api/src/services/assessmentsService.ts
Labels: enhancement

#577 #570 Implement working functionality for the POST /curriculum route
  api/src/assets/data.ts
  api/src/middleware/__tests__/assessmentsRouter.ts
  api/src/middleware/assessmentsRouter.ts
  api/src/services/__tests__/assessmentsService.ts
  api/src/services/assessmentsService.ts
Labels: enhancement

#582 #557 Implement working functionality for the DELETE /program/:programAssessmentId route
  api/src/middleware/__tests__/assessmentsRouter.ts
  api/src/middleware/assessmentsRouter.ts
  api/src/services/assessmentsService.ts
Labels: enhancement

#578 #564 Implement working functionality for the PUT /assessments/submissions/:submissionId
  api/src/middleware/assessmentsRouter.ts
  api/src/services/assessmentsService.ts
Labels: enhancement

#581 #576 Implement working functionality for the PUT /curriculum/:curriculumAssessmentId route
  api/src/services/assessmentsService.ts
Labels: enhancement

#583 #518 View template of assessments list
  webapp/src/components/AssessmentsListPage.tsx
  webapp/src/components/AssessmentsListTable.tsx
  webapp/src/components/AssessmentsListTabs.tsx
  webapp/src/types/api.d.ts
Labels: enhancement

#580 575 assessment submissions list
  webapp/src/components/AssessmentSubmissionsListPage.tsx
Labels: enhancement

#584 #579 Assessments detail page needs to be wired up to the backend
  webapp/src/components/App.tsx
  webapp/src/components/AssessmentDetailPage.tsx
  webapp/src/components/AssessmentSubmissionsListPage.tsx
Labels: enhancement

#586 #565 Delete an existing program assessment in the database
  api/src/assets/data.ts
  api/src/middleware/__tests__/assessmentsRouter.ts
  api/src/middleware/assessmentsRouter.ts
  api/src/services/__tests__/assessmentsService.ts
  api/src/services/assessmentsService.ts
Labels: enhancement

#587 #572 get program assessment route
  api/src/assets/data.ts
  api/src/middleware/__tests__/assessmentsRouter.ts
  api/src/middleware/assessmentsRouter.ts
  api/src/services/assessmentsService.ts
Labels: enhancement
